version: '2.2'
services:
  es:
    image: elasticsearch:6.8.1
    container_name: es
    hostname: es
    environment:
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=true
    volumes:
      - ./es:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      graph:
        ipv4_address: 192.168.12.10
  cassandra:
    image: cassandra:3.11.0
    container_name: cassandra
    hostname: cassandra
    ports:
      - 7000:7000
      - 7199:7199
      - 9042:9042
    depends_on:
      - es
    networks:
      graph:
        ipv4_address: 192.168.12.11
    volumes:
      - ./cassandra:/var/lib/cassandra/
  janusgraph:
    container_name: janusgraph
    image: janusgraph/janusgraph:0.4.0
    ports:
      - 8182:8182
    depends_on:
      - cassandra
    networks:
      graph:
        ipv4_address: 192.168.12.12
    volumes:
      - ./janusgraph.properties:/etc/opt/janusgraph/janusgraph.properties:ro
      - ./gremlin-server.yaml:/etc/opt/janusgraph/gremlin-server.yaml:ro
networks:
  graph:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24